### ISSUE TITLE
Question: BetterChat - Colorize custom Chat Formatting symbol 

### ISSUE THREAD

**Issue by MnkyArts** [LaserHydra/Plugins#1]
Hello, i just had a little question, i am currently using your BetterChat Plugin and im trying to add to the Chat Formatting a "|" now my question: is it possible to colorize the "|" ?

example with hashcode: "Chat": "{Title} #292929| {Username}: {Message}"

**Comment by LaserHydra** [comment]
This is not the correct place for BetterChat questions. Next time visit https://umod.org/plugins/betterchat

To manually color something, you can use color tags:
[#292929]My Text is colored[/#]
